version: '3.7'

# x-aws-cluster: ECS cluster ID
x-aws-vpc: arn:aws:ec2:${AWS_DEFAULT_REGION}:${AWS_ACCOUNT_ID}:vpc/${AWS_VPC_ID}
# x-aws-loadbalancer: ${ELB_ARN}

services:
  webserver:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/shepherd:webserver
    platform: linux/amd64
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
  scanner:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/shepherd:scanner
    platform: linux/amd64
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 16G

networks:
  default:
    external: true
    name: ${AWS_SECURITY_GROUP_ID}