version: '3.7'

services:
  scanner:
    hostname: ${IMAGE_REPO:-dummy}-shepherd-scanner
    build: 
      context: ./services
      target: scanner
    environment: 
      DB_HOST: ${DB_HOST:-pgdb-seeder}
      PROCESS_NAME: scanner
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
      HOST_URL: ${HOST_URL:-https://arweave.net}
      GQL_URL: ${GQL_URL:-https://arweave-search.goldsky.com/graphql}
    restart: always
  webserver:
    build: 
      context: ./services
      target: webserver
    environment: 
      DB_HOST: ${DB_HOST:-pgdb-seeder}
      PROCESS_NAME: webserver
      SLACK_WEBHOOK: ${SLACK_WEBHOOK:-}
      SLACK_POSITIVE: ${SLACK_POSITIVE:-}
      HOST_URL: ${HOST_URL:-https://arweave.net}
      GQL_URL: ${GQL_URL:-https://arweave-search.goldsky.com/graphql}
      BLACKLIST_ALLOWED: ${BLACKLIST_ALLOWED:-}
      RANGELIST_ALLOWED: ${RANGELIST_ALLOWED:-}
      GW_URLS: ${GW_URLS:-}
    ports: 
      - '80:80'
    restart: always
    depends_on:
      - scanner
  
