version: '3.7'

services:
  pgdb-seeder:
    build: 
      context: ./infra-local/postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: arblacklist
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    # ports:
    #   - '5432:5432'
  scanner:
    depends_on: 
      - pgdb-seeder

volumes:
  pgdata:
  # minio:
